#!/bin/bash
set -e

read -p "Load files, graph and flat meta model to all studies.  Do you want to proceed? (yes/no) " yn

case $yn in
	yes ) echo ok, we will proceed;;
	no ) echo exiting...;
		exit;;
	* ) echo invalid response;
		exit 1;;
esac


./load_all Alzheimers aced-development-ohsu-data-bucket
./load_all Alcoholism aced-development-ohsu-data-bucket
./load_all Breast_Cancer aced-development-manchester-data-bucket
./load_all Diabetes aced-development-ucl-data-bucket
./load_all Lung_Cancer aced-development-manchester-data-bucket
./load_all Prostate_Cancer aced-development-stanford-data-bucket
./load_all Colon_Cancer aced-development-stanford-data-bucket
