#!/bin/bash
set -e

if [ -z "$1" ]; then
    echo "Please provide a study name"
    exit 1
fi

if [ -z "$2" ]; then
    echo "Please provide a bucket name"
    exit 1
fi

study="$1"
bucket="$2"

schema=https://aced-public.s3.us-west-2.amazonaws.com/aced.json

# the user (outside of the etl pod) has already loaded the data - this line only applies to synthetic data we are loading here
#aced_submission files upload --program aced --project $study --bucket_name $bucket  --document_reference_path studies/$study  --duplicate_check

# test if the study has been simplified
if [ ! -f studies/$study/extractions/ResearchStudy.ndjson ]; then
    echo "Study has not been simplified.  Simplifying now..."
    iceberg data simplify studies/$study/ studies/$study/extractions/ --schema_path  $schema --dialect PFB
fi
# load all meta into graph db
aced_submission meta graph upload --source_path studies/$study/extractions/ --project_id aced-$study  --dictionary_path $schema
# load patient file if it exists
if [ -f studies/$study/extractions/Patient.ndjson ]; then
  aced_submission meta flat denormalize-patient --input_path studies/$study/extractions/Patient.ndjson
  aced_submission meta flat load --project_id aced-$study --index patient --path studies/$study/extractions/Patient.ndjson --schema_path  $schema
fi
# load DocumentReference if it exists
if [ -f studies/$study/extractions/DocumentReference.ndjson ]; then
  aced_submission meta flat load --project_id aced-$study --index file --path studies/$study/extractions/DocumentReference.ndjson --schema_path  $schema
fi
# load Observation if it exists
if [ -f studies/$study/extractions/Observation.ndjson ]; then
  aced_submission meta flat load --project_id aced-$study --index observation --path studies/$study/extractions/Observation.ndjson --schema_path  $schema
fi


