#!/bin/bash
set -e

if [ -z "$1" ]; then
    echo "Please provide a study name"
    exit 1
fi

if [ -z "$2" ]; then
    echo "Please provide a bucket name"
    exit 1
fi

study="$1"
bucket="$2"

schema=https://aced-public.s3.us-west-2.amazonaws.com/simplified-fhir.json

#aced_submission files upload --program aced --project $study --bucket_name $bucket  --document_reference_path studies/$study  --duplicate_check
aced_submission meta graph upload --source_path studies/$study/extractions/ --program aced --project $study  --dictionary_path $schema
aced_submission meta flat denormalize-patient --input_path studies/$study/extractions/Patient.ndjson
aced_submission meta flat load --project_id aced-$study --index patient --path studies/$study/extractions/Patient.ndjson --schema_path  $schema
aced_submission meta flat load --project_id aced-$study --index file --path studies/$study/extractions/DocumentReference.ndjson --schema_path  $schema
aced_submission meta flat load --project_id aced-$study --index observation --path studies/$study/extractions/Observation.ndjson --schema_path  $schema

