#!/bin/bash
set -e

#
# load gen3 graph and flat meta model
# env vars:
#  study: name of study to load (required) ie Alzheimers path to study data is studies/$study
#  project_id: project id to load to (required) ie <institution>-<project> eg ohsu-myproject
#  bucket: bucket to load from (optional) ie aced-development-ohsu-data-bucket
#  schema: path to schema (optional) default https://aced-public.s3.us-west-2.amazonaws.com/aced.json
#


#
# check setup of pod complete
#

if [[ ! -f ~/config.yaml ]]; then
    echo "Please setup config.yaml with from iceberg-schema-tools"
    exit 1
fi


#
# check expected env vars
#
if [ -z "$study" ]; then
    echo "Please provide a study name"
    exit 1
fi

if [ -z "$project_id" ]; then
    echo "Please provide a project_id (program-project)"
    exit 1
fi


if [ -z "$schema" ]; then
    schema=https://aced-public.s3.us-west-2.amazonaws.com/aced.json
fi

echo "Using default schema $schema"


# the user (outside of the etl pod) has already loaded the data
# typically we are only loading  synthetic data here
if [ ! -z "$bucket" ]; then
  aced_submission files upload --program aced --project $study --bucket_name $bucket  --document_reference_path studies/$study  --duplicate_check
fi


# test if the study has been simplified
if [ ! -f studies/$study/extractions/ResearchStudy.ndjson ]; then
    echo "Study has not been simplified.  Simplifying now..."
    iceberg data simplify studies/$study/ studies/$study/extractions/ --schema_path  $schema --dialect PFB
fi

# load all meta into graph db
aced_submission meta graph upload --source_path studies/$study/extractions/ --project_id $project_id  --dictionary_path $schema
# load patient file if it exists
if [ -f studies/$study/extractions/Patient.ndjson ]; then
  aced_submission meta flat denormalize-patient --input_path studies/$study/extractions/Patient.ndjson
  aced_submission meta flat load --project_id $project_id --index patient --path studies/$study/extractions/Patient.ndjson --schema_path  $schema
else
  aced_submission meta flat load --project_id $project_id --index patient --path /dev/null --schema_path  $schema
fi
# load DocumentReference if it exists
if [ -f studies/$study/extractions/DocumentReference.ndjson ]; then
  aced_submission meta flat load --project_id $project_id --index file --path studies/$study/extractions/DocumentReference.ndjson --schema_path  $schema
else
  aced_submission meta flat load --project_id $project_id --index file --path /dev/null --schema_path  $schema
fi
# load Observation if it exists
if [ -f studies/$study/extractions/Observation.ndjson ]; then
  aced_submission meta flat load --project_id $project_id --index observation --path studies/$study/extractions/Observation.ndjson --schema_path  $schema
else
  aced_submission meta flat load --project_id $project_id --index observation --path /dev/null --schema_path  $schema
fi

echo "Done loading meta data for $study to $project_id, please run \"gen3_util projects add resource $project_id\" to add policies to Arborist"
