name: Build and publish CALYPR ETL image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    # Required to simulate different architectures (e.g., ARM on AMD64 runner)
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # Required to use the 'docker buildx' command
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Extract Metadata (Tags/Labels)
      id: meta
      run: |
        # Calculate the branch-based tag
        BRANCH=$(echo ${GITHUB_REF#refs/*/} | tr / _)
        REPO=quay.io/ohsu-comp-bio/aced-etl
        
        # Prepare the tag list
        TAGS="$REPO:$BRANCH"
        if [[ $BRANCH == 'main' ]]; then
          TAGS="$TAGS,$REPO:latest"
        fi
        echo "::set-output name=tags::$TAGS"

    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: ./etl-job
        # Define the architectures you want to support here:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}