# Workflow for building the ACED ETL image and pushing it to the quay.io repository
#
# Optionally debug via SSH
# Ref: https://fleetdm.com/engineering/tips-for-github-actions-usability
#
# To use this step uncomment and place anywhere in the build steps. The build will pause on this step and
# output a ssh address associated with the Github action worker. Helpful for debugging build steps and
# and intermediary files/artifacts.
#
# - name: Setup tmate session
#   uses: mxschmitt/action-tmate@v3

name: Build and publish ACED ETL image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Build and push image
      run: |
        # Set Image tag to the branch name
        BRANCH=$(echo ${GITHUB_REF#refs/*/} | tr / _)
        echo "IMAGE_TAG=$IMAGE_TAG"

        # Login to Quay.io and build image
        docker login quay.io
        REPO=quay.io/ohsu-comp-bio/aced-etl
        docker build -t $REPO:${{ env.IMAGE_TAG }} ./etl-job
        
        # Add 'latest' tag to 'main' image
        if [[ $IMAGE_TAG == 'main' ]]; then
          docker image tag $REPO:main $REPO:latest
        fi

        # Push the tagged image to Quay.io
        docker push --all-tags $REPO
